# Generated by Django 4.2.25 on 2026-02-24 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='categories.subcategory'),
        ),
    ]
