# Generated by Django 4.2.25 on 2026-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_remove_providerprofile_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerprofile',
            old_name='title',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='place',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='post',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_covers/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='full_address',
            field=models.TextField(default='Not updated '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_logos/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
