# Generated by Django 6.0.2 on 2026-03-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_subcategory_image'),
        ('services', '0002_remove_service_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='categories.subcategory'),
            preserve_default=False,
        ),
    ]
