# Generated by Django 6.0.2 on 2026-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_offer_price_service_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_type',
            field=models.CharField(choices=[('stay', 'Stay (Hotel/Resort)'), ('timeslot', 'Time Slot (Cafe/Food)'), ('ride', 'Ride (Transport)'), ('event', 'Event (Tours/Activities)')], default='event', max_length=20),
        ),
    ]
